config/routes.rb
Coursequestionbank::Application.routes.draw do

  root :to => 'problems#home'

  match  'auth/:provider/callback' => 'session#create'
  get 'auth/bypass/:user_id' => 'session#bypass', :as => 'bypass'
  post 'logout' => 'session#destroy'
  get  'auth/failure' => 'session#failure'
  get 'login' => 'session#login', :as => 'login'
  get 'upload' => 'upload#index', :as => 'upload'
  post 'upload' => 'upload#upload', ":as" => 'upload'

  resources :problems
  get 'problems/tags/:tag_names' => 'problems#view_tags', :as => 'view_tags'
  post 'problems/filters' => 'problems#set_filters', :as => 'set_filters'
  post 'problems/:id/tags/add' => 'problems#add_tags', :as => 'add_tags'
  post 'problems/:id/tags/remove' => 'problems#remove_tags', :as => 'remove_tags'
  post 'update_multiple_tags' => 'problems#update_multiple_tags'

  get 'problems/:id/supersede' => 'problems#supersede', :as => 'supersede'

  post 'problems/:id/minorupdate' => 'problems#minorupdate', :as => "minorupdate"
  get 'problems/:id/minorupdate' => 'problems#minorupdate', :as => "minorupdate"

  post 'problems/edit_minor' => 'problems#edit_minor', :as => "edit_minor"

  get 'problems/:id/history' => 'problems#view_history', :as => 'problem_history'

  get 'profile' => 'instructors#show', :as => 'profile'
  
  get 'admin' => 'instructors#admin', :as => 'admin'
  post 'admin/instructor' => 'instructors#update_instructor', :as => 'update_instructor'

  resources :studentanswers

  resources :collections
  post 'collections/search/' => 'collections#search', :as => 'search_collection'
  get 'collections/:id/export' => 'collections#export', :as => 'export'
  get 'collections/:id/preview' => 'collections#preview', :as => 'preview'
  get 'finalize_upload' => 'collections#finalize_upload'
  get 'collections/search/' => 'collections#search', :as => 'search_collection'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  attr_accessible :last_used, :name, :description, :is_public, :color, :access_level
  validates :name, presence: true #, uniqueness: true for now this is bad
  has_and_belongs_to_many :problems
  belongs_to :instructor
  # scope :collection, ->(collection_name) { where(name: collection_name) }
  scope :mine_or_public, ->(user) {where('instructor_id=? OR access_level<?', "#{user.id}", '3')}
  scope :public, where("access_level < 3")

  searchable do
    text :name
    text :description
    integer :access_level
    integer :instructor_id
  end

  def self.filter(user, searchers)


    collections = Collection.search do

      any_of do

        with(:access_level, 1)
        with(:instructor_id, user.uid)
        if user.privilege != "Student"

          with(:access_level, 2)
        end
      end

      fulltext searchers[:search] + "~"
    end

    if !collections.nil?
      results = collections.results
    end
    return results
  end


  def set_attributes(params)
    # debugger
    self.name = params[:name] if params[:name]
    self.description = params[:description] if params[:description]
    self.is_public = params[:is_public] if params[:is_public]
    self.access_level = params[:access_level] if params[:access_level]
    if ['Public', 'Share', 'Private'].include? params[:privacy]
      self.is_public = params[:privacy] == 'Public'
      self.access_level = ["Public", "Share", "Private"].index(params[:privacy])
    end
  end

  # def self.search(search)
  #   # debugger
  #   # if Problem.count != 0
  #     collections = Collection.search do
  #       # debugger
  #       any_of do
  #         with(:search, collection.name)
  #         with(:search, collection.description)
  #       end
  #     end
  #   end

  # def get_access_level
  #   if self.access_level.nil?
  #       self.access_level = 0
  #     else
  #       self.access_level = 1
  #     end
  #   end
  #   return self.access_level
  # end

  def export(format)
    if problems.empty?
      return nil
    else
      if format == 'ruql'
        print_name = (description.nil? || description.strip.empty?) ? name : name + ': ' + description
        source = "quiz #{print_name.inspect} do\n"
        problems.each do |prob|
          prob_source = prob.ruql_source.lines.map{|x| '  ' + x}.join
          source += "\n#{prob_source}\n"
        end
        source += "\nend"
      else
        export_quiz = Quiz.new(name, nil, {:questions => problems.map {|problem| Question.from_JSON(problem.json)}})
        export_quiz.render_with(format)
      end
    end
  end

  # def public?
  #   self.is_public
  # end

  def self.access_levels
    %w{Public Share Private}
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  load_and_authorize_resource

  @@defaults = HashWithIndifferentAccess.new({'search' => ""})



  def new
    @collection = Collection.new
  end

  def index
    session[:filters] = nil
    @heading = 'Public collections'
    @instructor = Instructor.find_by_id(@current_user)

    if @current_user.get_privilege == "Student"
      @collections = Collection.where(:access_level => 1)
    else
      @collections = Collection.where(:access_level => 1) + Collection.where(:access_level => 2)
    end
    # debugger
  end

  def search
    session[:filter] ||= HashWithIndifferentAccess.new(@@defaults)
    session[:filter][:search] = params[:search]

    @search = session[:filter][:search]

    if @search.empty? || @collections.nil?
      redirect_to collections_path
    end

    @collections = Collection.filter(@current_user, session[:filter].clone)
  end

  def edit
    @collection = Collection.find(params[:id])
    @problems = @collection.problems
  end

  # creates a new collection with user specified values and sets as current collection
  def create
    collection = @current_user.collections.create
    collection.set_attributes(params)

    if not collection.valid?
      collection_errors(collection)
      redirect_to :back and return
    else
      collection.save
    end
    redirect_to collection_path(:id => collection.id)
  end

  def show
    @collection = Collection.find(params[:id])
    @problems = @collection.problems
  end

  def update

    collection = Collection.find(params[:id])
    collection.set_attributes(params)

    if not collection.valid?
      collection_errors(collection)
      redirect_to :back and return
    else
      if params[:access_level].nil? == false
        name = {"Public" => 1, "Share" => 2, "Private" => 3}
        level = name[params[:access_level]]
        collection.access_level = level
      end
      collection.save

    end
    redirect_to collection_path(:id => collection.id)
  end

  def destroy
    Collection.find(params[:id]).destroy
    flash[:notice] = 'Collection deleted'
    redirect_to profile_path
  end

  def export
    @collection = Collection.find(params[:id])

    @ruql_code = @collection.export('ruql') rescue "(error rendering RuQL)"
    @html_code = @collection.export('Html5') rescue "(error rendering HTML)"
    @edx_code = @collection.export('EdXml') rescue "(error rendering Edml)"
    @autoqcm_code = @collection.export('AutoQCM') rescue "(error rendering AutoQCM)"

    if not @html_code
      flash[:notice] = 'Cannot export an empty collection! Add some questions to your collection first!'
      redirect_to collection_path(:id => @collection.id)
    end
  end

  def preview
    ruql_code = Collection.find(params[:id]).export('ruql')
    render :text => ruql_code
  end

  def finalize_upload
    @collections = params[:ids].map{|collection_id| Collection.find(collection_id)}
    @collections.each{|c| authorize! :read, c}
  end

  private

  def collection_errors(collection)
    flash[:notice] =  collection.errors.messages.map {|key, value| key.to_s + ' ' + value.to_s}.join ' ,'
  end

end

app/helpers/collections_helper.rb
module CollectionsHelper
  def num_problems(collections)
    collections.inject(0){|sum, c| c.problems.size + sum}
  end
end

app/views/collections/_edit_collection.html.haml
%h3.section_title 
  Edit Collection
  = link_to collection.name, collection_path(:id => collection.id)

%div.section_options
  = form_tag collection_path(:id => collection.id), :method => :delete do
    = button_tag :type => 'submit', :class => 'btn btn-default', :id => 'delete_collection_button' do
      %span.glyphicon.glyphicon-trash
      Delete Collection
      

%div.section_body
  = render :partial => 'collections/form', :locals => {:collection => collection}
  
  = render :partial => 'problems/problem_table', 
            :locals => {:problems => collection.problems, :columns => [:checkbox, :problem, :tags],
                        :group_id => collection.id, :empty_msg => 'This collection is empty'}

app/views/collections/_filter.html.haml
= form_tag search_collection_path, :method => :post, :id => 'filter-form' do

  %div.form-group
    = label_tag :name, 'Search:'
    = text_field_tag :name, session[:name], class: 'form-control', placeholder: 'Name of the Collection'
  %hr
    = submit_tag 'Search', :class => 'btn btn-primary'
 

app/views/collections/_form.html.haml
// = form_for(collection, :html => {:class => 'form-inline'}) do |f|
//   = f.label :name
//   = f.text_field :name, :class => 'form-control'
//   = f.label :description
//   = f.text_field :description, :class => 'form-control', :placeholder => 'Write a description'
//   = f.select :color, ['Red', 'Blue', 'Green', 'Yellow', 'Black', 'Purple'], :class => 'form-control'
//   = f.label 'Mark as public?'
//   = f.check_box :is_public, :class => 'form-control'
//   %div.form-group
//     = f.submit 'Update', class: 'btn btn-primary'
//     =link_to collection_path(collection), :class => 'btn btn-default', method: :delete, :confirm => 'Delete this collection?', id: 'Delete' do
//       %span.glyphicon.glyphicon-trash
//       Delete Collection
//     =link_to export_path(:id => collection), :class => 'btn btn-default', id: 'Export' do
//       %span.glyphicon.glyphicon-export
//       Export


- if local_assigns[:new]
  - submit_path = [collections_path, :post]
- else
  - submit_path = [collection_path(:id => collection.id), :put]


= form_tag submit_path[0], :method => submit_path[1], :class => 'collection_form form-horizontal' do
  
  %div.form-group
    = label_tag :name, 'Name:', :class => 'col-xs-12 col-sm-2 control-label'
    %div.col-xs-12.col-sm-10
      = text_field_tag :name, collection.name, :id => nil, :class => 'form-control', :placeholder => 'Collection name'
  
  %div.form-group
    = label_tag :description, 'Description:', :class => 'col-xs-12 col-sm-2 control-label'
    %div.col-xs-12.col-sm-8
      = text_area_tag :description, collection.description, :id => nil, :class => 'form-control', :placeholder => 'Write a description'
  
  %div.form-group
    %div.col-sm-2
    %div.col-xs-12.col-sm-10
      - level = ["", "Public", "Share", "Private"][collection.access_level]
      = select_tag :access_level, options(Collection.access_levels, level), :id => "dropdown", :class => 'form-control', :style=>"max-width:10%"


  %div.form-group
    %div.col-sm-2
    %div.col-sm-10.col-xs-12
      = submit_tag (local_assigns[:new] ? 'Create' : 'Update'), :class => 'btn btn-primary'

app/views/collections/_view_by_tag.html.haml
%h3.section_title 
  Viewing Problems with Tag Dup
  // = link_to collection.name, collection_path(:id => collection.id)
  
%div.section_body
  = render :partial => 'problems/problem_table', 
            :locals => {:problems => @collection.problems, :columns => [:checkbox, :problem, :tags],
                        :group_id => @collection.id, :empty_msg => 'This collection is empty'}

app/views/collections/edit.html.haml
= render :partial => 'edit_collection', :locals => {:collection => @collection}

app/views/collections/export.html.haml
%div.section_title 
  %h3 
    Export Collection
    = link_to @collection.name, collection_path(:id => @collection.id)
  %h4= @collection.description
  - if @collection.is_public
    %h5= @collection.instructor.name
  
%div.section_options
  = link_to "Preview quiz", preview_path(:id => @collection.id), :class => 'btn btn-info'

%div.section_body
  %ul.nav.nav-tabs
    // %li
    //   %a{"data-toggle" => "tab", :href => "#sectionA"} Preview Quiz
    %li.active
      %a{"data-toggle" => "tab", :href => "#section_ruql"} RuQL Code
    %li
      %a{"data-toggle" => "tab", :href => "#section_html"} HTML Code
    %li
      %a{"data-toggle" => "tab", :href => "#section_edx"} EdX Code
    %li
      %a{"data-toggle" => "tab", :href => "#section_autocqm"} AutoQCM Code
  
  %div.tab-content#export-content
    // #sectionA.tab-pane.fade.in.active
    //   %h3 Preview Quiz
    //   %h6
    //     = @html_code.html_safe
    %div#section_ruql.tab-pane.active
      %h3 RuQL Code
      %textarea.source_field{:wrap => 'hard', :readonly => 'true'}
        = preserve @ruql_code
    %div#section_html.tab-pane
      %h3 HTML Code
      %textarea.source_field{:wrap => 'hard', :readonly => 'true'}
        = preserve @html_code
    %div#section_edx.tab-pane
      %h3 EdX Code
      %textarea.source_field{:wrap => 'hard', :readonly => 'true'}
        = preserve @edx_code
    %div#section_autocqm.tab-pane
      %h3 AutoQCM Code
      %textarea.source_field{:wrap => 'hard', :readonly => 'true'}
        = preserve @autoqcm_code

    

app/views/collections/finalize_upload.html.haml
%h3.section_title Upload successful! #{num_problems(@collections)} problems found in #{@collections.size} collections.
  
- @collections.each do |collection|
  %hr
  = render :partial => 'edit_collection', locals: {collection: collection}

// = render :partial => 'view_by_tag'

app/views/collections/index.html.haml
%h3.section_title= @heading

%div.section_options
  - if can? :create, Collection
    = link_to 'New collection', new_collection_path, :class => 'btn btn-primary'
    = link_to 'Upload questions', upload_path, :class => 'btn btn-primary'


- if can? :create, Collection
  %div#filter-sidebar
    = form_tag search_collection_path do
      = field_set_tag do
        = label_tag :search, 'Search:'
        = text_field_tag :search, nil, class: 'form-control', placeholder: 'Name of the Collection'
        %br
        = submit_tag 'Search', :class => 'btn btn-primary'
    %hr

  %div#filter-content.container-fluid
    - if @collections.empty?
      %h4.section_body You have no collections.

    - else
      %div.table-responsive.section_body
        %table.table.table-striped
          %thead
            %tr
              %th Name
              %th Owner
              %th # Questions
              %th Description
              %th Last used
              %th Privacy

          %tbody
            - @collections.each do |collection|
              %tr
                %td= link_to collection.name.truncate(35), collection_path(:id => collection.id), :class => 'btn btn-link', :title => collection.name
                %td= collection.instructor.try(:name)
                %td= collection.problems.length
                %td= collection.description
                %td= collection.last_used
                - name = ["", "Public", "Share", "Private"]
                - level = collection.access_level
                %td= name[level]

- else
  - if @collections.empty?
    %h4.section_body You have no collections.

  - else
    %div.table-responsive.section_body
      %table.table.table-striped
        %thead
          %tr
            %th Name
            %th Owner
            %th # Questions
            %th Description
            %th Last used
            %th Privacy

        %tbody
          - @collections.each do |collection|
            %tr
              %td= link_to collection.name.truncate(35), collection_path(:id => collection.id), :class => 'btn btn-link', :title => collection.name
              %td= collection.instructor.try(:name)
              %td= collection.problems.length
              %td= collection.description
              %td= collection.last_used
              - name = ["", "Public", "Share", "Private"]
              - level = collection.access_level
              %td= name[level]

app/views/collections/new.html.haml
%h3.section_title 
  New Collection


%div.section_body
  = render :partial => 'collections/form', :locals => {:collection => @collection, :new => true}

app/views/collections/search.html.haml
%h3.section_title= @heading

%div.section_options
  - if can? :create, Collection    
    = link_to 'New collection', new_collection_path, :class => 'btn btn-primary'
    = link_to 'Upload questions', upload_path, :class => 'btn btn-primary'

%div#filter-sidebar
  = form_tag search_collection_path do
    = field_set_tag do
      = label_tag :search, 'Search:'
      = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search'
      %br
      = submit_tag 'Search', :class => 'btn btn-primary'
  %hr


%div#filter-content.container-fluid
  - if @collections.nil? || @collections.empty?
    %h4.section_body No collection matches.

  - else
    %div.table-responsive.section_body
      %table.table.table-striped
        %thead
          %tr
            %th Name
            %th Owner
            %th # Questions
            %th Description
            %th Last used
            %th Privacy

        %tbody
          - @collections.each do |collection|
            %tr
              %td= link_to collection.name.truncate(35), collection_path(:id => collection.id), :class => 'btn btn-link', :title => collection.name
              %td= collection.instructor.try(:name)
              %td= collection.problems.length
              %td= collection.description
              %td= collection.last_used
              - name = ["", "Public", "Share", "Private"]
              - level = collection.access_level
              %td= name[level]

app/views/collections/show.html.haml
%div.section_title
  - name = ["", "Public", "Share", "Private"]
  - level = @collection.access_level
  %h3 #{name[level]} Collection #{@collection.name}
  %h4= @collection.description
  - if @collection.is_public
    %h5= @collection.instructor.name

%div.section_options
  - if can? :manage, @collection
    = link_to "Edit this collection", edit_collection_path(:id => @collection.id), :class => 'btn btn-primary'

  = link_to export_path(:id => @collection.id), :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-export
    Export

%div.section_body
  / - if can? :manage, @collection
  = render :partial => 'problems/problem_table',
            :locals => {:problems => @collection.problems, :columns => [:checkbox, :problem, :tags],
                        :group_id => @collection.id, :empty_msg => 'This collection is empty'}
  / - else
  /   = render :partial => 'problems/student_problem_table',
  /             :locals => {:problems => @collection.problems, :columns => [:checkbox, :problem, :tags],
  /                         :group_id => @collection.id, :empty_msg => 'This collection is empty'}