config/routes.rb
Coursequestionbank::Application.routes.draw do

  root :to => 'problems#home'

  match  'auth/:provider/callback' => 'session#create'
  get 'auth/bypass/:user_id' => 'session#bypass', :as => 'bypass'
  post 'logout' => 'session#destroy'
  get  'auth/failure' => 'session#failure'
  get 'login' => 'session#login', :as => 'login'
  get 'upload' => 'upload#index', :as => 'upload'
  post 'upload' => 'upload#upload', ":as" => 'upload'

  resources :problems
  get 'problems/tags/:tag_names' => 'problems#view_tags', :as => 'view_tags'
  post 'problems/filters' => 'problems#set_filters', :as => 'set_filters'
  post 'problems/:id/tags/add' => 'problems#add_tags', :as => 'add_tags'
  post 'problems/:id/tags/remove' => 'problems#remove_tags', :as => 'remove_tags'
  post 'update_multiple_tags' => 'problems#update_multiple_tags'

  get 'problems/:id/supersede' => 'problems#supersede', :as => 'supersede'

  post 'problems/:id/minorupdate' => 'problems#minorupdate', :as => "minorupdate"
  get 'problems/:id/minorupdate' => 'problems#minorupdate', :as => "minorupdate"

  post 'problems/edit_minor' => 'problems#edit_minor', :as => "edit_minor"

  get 'problems/:id/history' => 'problems#view_history', :as => 'problem_history'

  get 'profile' => 'instructors#show', :as => 'profile'
  
  get 'admin' => 'instructors#admin', :as => 'admin'
  post 'admin/instructor' => 'instructors#update_instructor', :as => 'update_instructor'

  resources :studentanswers

  resources :collections
  post 'collections/search/' => 'collections#search', :as => 'search_collection'
  get 'collections/:id/export' => 'collections#export', :as => 'export'
  get 'collections/:id/preview' => 'collections#preview', :as => 'preview'
  get 'finalize_upload' => 'collections#finalize_upload'
  get 'collections/search/' => 'collections#search', :as => 'search_collection'

end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_filter :set_filter_options
  load_and_authorize_resource
 @@defaults = HashWithIndifferentAccess.new({
   'search' => "",
   'tags' => [],
   'sort_by' => 'Relevancy',
   'problem_type' => [],
   'collections' => [],
   'bloom_category' => [],
   'show_obsolete' => false,
   'per_page' => 60, 'page' => 1 })

  def set_filter_options
    session[:filters] ||= HashWithIndifferentAccess.new(@@defaults)

    @@defaults.each do |key, value|
      session[:filters][key] ||= value
    end

    session[:filters][:page] = nil
    session[:filters] = session[:filters].merge params.slice(:page, :per_page)
  end

  def set_filters

    session[:filters] = session[:filters].merge params.slice(:search, :tags, :sort_by)

    if session[:filters][:tags].is_a? String
      session[:filters][:tags] = self.class.parse_list session[:filters][:tags]
    end

    ["problem_type", "bloom_category"].each do |sub|
      session[:filters]["#{sub}"] = []
      if params["#{sub}"]
          params["#{sub}"].each do |key, value|
              session[:filters]["#{sub}"] << key if value == "1"
          end
        end
    end

    # session[:filters][:problem_type] = []
    # if params[:problem_type]
    #   params[:problem_type].each do |key, value|
    #       session[:filters][:problem_type] << key if value == "1"
    #   end
    # end
    #
    # session[:filters][:bloom_category] = []
    # if params[:bloom_category]
    #   params[:bloom_category].each do |key, value|
    #       session[:filters][:bloom_category] << key if value == "1"
    #   end
    # end

    session[:filters][:collections] = []
    if params[:collections]
      params[:collections].each do |key, value|
          session[:filters][:collections] << Integer(key) if value == "1"
      end
    end

    if session[:filters][:collections].include?(0)
      session[:filters][:collections] = []
    end

    session[:filters][:show_obsolete] = params[:show_obsolete] == "1"

    redirect_to problems_path
  end

  def home
      redirect_to problems_path
  end

  def index
    # debugger
    if can? :manage, Collection and @current_user.collections
      @collections = @current_user.collections + Collection.where(:access_level => 2) + Collection.where(:access_level => 3)
    else
      @collections = Collection.where(:access_level => 3)
    end
    # @is_student = cannot? :manage Collections

    @problems = Problem.filter(@current_user, session[:filters].clone, Problem.find_by_id(flash[:bump_problem]))
    # debugger
  end

  def new
    @ruql_source = flash[:ruql_source]
  end

  def create
    parent_uid = params[:parent_uid]
    if parent_uid
      previous_version = Problem.find_by_uid(params[:parent_uid])
      if !previous_version
        flash[:error] = "Could not find #{params[:parent_uid]}, using default previous question"
      end
    end

    privacy = params[:privacy] ? params[:privacy].strip.downcase : nil
    category = Problem.all_bloom_categories.include?(params[:category]) ? params[:category] : nil
    collections = []
    if params[:collections]
      params[:collections].each do |key, value|
        col = Collection.find(key)
        authorize! :manage, col
        collections << col
      end
    end

    begin
      problem = RuqlReader.read_problem(@current_user, params[:ruql_source])
      problem.previous_version = previous_version
      problem.is_public = privacy == 'public'
      problem.access_level = 1
      problem.bloom_category = category
      problem.save
      problem.add_tags(self.class.parse_list params[:tag_names])
      collections.each {|c| c.problems << problem}
      flash[:bump_problem] = problem.id
      Problem.reindex
      Sunspot.commit
      dups_found = Problem.handle_dups(@current_user, problem.id) #check for dups
      if dups_found
        flash[:notice] = "Near-duplicate question may have been uploaded! See questions tagged with 'dup' and the new Question's UID. Click on tag to view potential matches. Mark undesired Questions as Obsolete. Remove dup tags when finished."
      end

    rescue Exception => e
      if request.xhr?
        render :json => {'error' => e.message}
      else
        flash[:error] = "Error in problem source: #{e.message}. A Question's unique ID may already exist in database."
        flash[:ruql_source] = params[:ruql_source]
        redirect_to :back
      end
      return
    end

    flash[:notice] = "Question created." if !flash[:notice]
    if request.xhr?
      render :json => {'error' => nil}
    else
      redirect_to problems_path
    end
  end

  def update
    problem = Problem.find(params[:id])

    if !params[:privacy].nil?

      authorize! :set_privacy, problem
      privacy = params[:privacy].downcase.strip
      if privacy == 'public'
        # problem.is_public = true
        problem.access_level = 2
      elsif privacy == 'share'
        problem.access_level = 3
      elsif privacy == 'private'
        # problem.is_public = false
        problem.access_level = 1
      else
        return
      end
      problem.save

      flash[:notice] = "Problem changed to #{privacy}" if !request.xhr?
    end

    if !params[:obsolete].nil?
      authorize! :set_obsolete, problem
      problem.obsolete = params[:obsolete] == '1'
      problem.save
      flash[:notice] = "Problem marked as #{'not ' if !problem.obsolete}obsolete" if !request.xhr?
    end

    if !params[:category].nil?
      authorize! :bloom_categorize, problem
      category = params[:category].downcase.strip
      category[0] = category[0].upcase
      if Problem.all_bloom_categories.include? category
        problem.bloom_category = category
        flash[:notice] = "Bloom category set to #{category}" if !request.xhr?
      elsif category == 'None'
        problem.bloom_category = nil
        flash[:notice] = "Bloom category removed" if !request.xhr?
      end
      problem.save
    end

    if !params[:collection].nil?
      target_collection = Collection.find(params[:collection])
      if !target_collection.problems.include? problem
        authorize! :add_problems, target_collection
        target_collection.problems << problem
        flash[:notice] = "Problem added to #{target_collection.name}" if !request.xhr?
      else
        authorize! :remove_problems, target_collection
        target_collection.problems.delete(problem)
        flash[:notice] = "Problem removed from #{target_collection.name}" if !request.xhr?
      end
      problem.save
    end

    if !params[:previous].nil?
        authorize! :set_previous, problem
        previous = Problem.find_by_uid(params[:previous])
        if previous
          problem.previous_version = previous
          problem.save
          flash[:notice] = "Problem parent set to #{params[:previous]}" if !request.xhr?
        else
          flash[:error] = "Problem #{params[:previous]} not found" if !request.xhr?
        end
    end

    if request.xhr?
      render :nothing => true
    else
      flash[:bump_problem] = problem.id
      redirect_to :back
    end
  end

  def add_tags
    problem = Problem.find(params[:id])
    tags = self.class.parse_list params[:tag_names]
    added = problem.add_tags(tags)
    if request.xhr?
      render :partial => "tags", locals: { problem: problem }
    else
      flash[:notice] = "Tags added" if added.size > 0
      flash[:bump_problem] = problem.id
      redirect_to :back
    end
  end

  def remove_tags
    problem = Problem.find(params[:id])
    tags = self.class.parse_list params[:tag_names]
    tags.each { |tag| problem.remove_tag tag }
    if request.xhr?
      render :nothing => true
    else
      flash[:notice] = "Tags removed"
      flash[:bump_problem] = problem.id
      redirect_to :back
    end
  end

  def view_tags
    session[:filters] = HashWithIndifferentAccess.new(@@defaults)
    @@defaults.each do |key, value|
      session[:filters][key] = value
    end

    session[:filters][:tags] = self.class.parse_list params[:tag_names]
    redirect_to problems_path
  end


  def update_multiple_tags
    new_tags = self.class.parse_list params[:tag_names]
    selected = params[:checked_problems] ? params[:checked_problems].keys : []
    if new_tags == []
      flash[:error] = "You need to enter a tag."
    elsif selected == []
      flash[:error] = "You need to select a problem."
    else
      selected.each do |problem_id|
        problem = Problem.find(problem_id)
        authorize! :add_tags, problem
        flash[:notice] = "Tags were added." if problem.add_tags(new_tags).size > 0
      end
    end
    redirect_to :back
  end

  def minorupdate
    @problem = Problem.find(params[:id])
    @ruql_source = flash[:ruql_source]
  end

  def supersede
    @problem = Problem.find(params[:id])
    @ruql_source = flash[:ruql_source]
  end

  def view_history
    @problem = Problem.find(params[:id])
    @history = @problem.history
  end

  def edit_minor

    new_problem = RuqlReader.read_problem(@current_user, params[:ruql_source])
    original_problem = Problem.find_by_uid(params[:parent_uid])

    if !new_problem[:json].nil?
      if original_problem[:json] != new_problem[:json]
        original_problem[:json] = new_problem[:json]
        original_problem.save

        flash[:notice] = "Question updated."
      else
        flash[:notice] = "Nothing changes."
      end

    end

    if request.xhr?
      render :json => {'error' => nil}
    else
      redirect_to problems_path
    end

  end

end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_add_collection_expand.html.haml
- previous = local_assigns[:previous] || nil
- source = @ruql_source || (previous && previous.ruql_source) || ''
- tags = (previous && previous.tags.map(&:name).join(', ')) || ''


= form_tag problems_path, :method => :post, :class => 'form-horizontal new-form' do
  %div.form-group
    = label_tag nil, 'Collections:', :class => 'col-xs-12 col-sm-2 control-label'
    %div.col-xs-12.col-sm-10.new-problem-collections
      - Collection.accessible_by(current_ability, :manage).each do |collection|
        %div.new-problem-collection
          = check_box_tag "collections[#{collection.id}]", 1,  !!(collection.problems.include? previous), class: 'checkbox', id: "collections_#{collection.id}"
          = label_tag "collections_#{collection.id}", collection.name.truncate(35), :title => collection.name

  %div.form-group
    %div.col-sm-2
    %div.col-xs-12.col-sm-10
      = select_tag :privacy, privacy_options(previous ? previous.is_public : false), :id => nil, :class => 'form-control'

  %div.form-group
    %div.col-sm-2
    %div.col-xs-12.col-sm-10
      %p.message
      - submit_msg = previous ? 'Supersede question' : 'Create question'
      = submit_tag submit_msg, :class => 'btn btn-primary'

app/views/problems/_add_to_collection.html.haml
- previous = local_assigns[:previous] || nil
- source = @ruql_source || (previous && previous.ruql_source) || ''
- tags = (previous && previous.tags.map(&:name).join(', ')) || ''


= form_tag problems_path, :method => :post, :class => 'form-horizontal new-form' do
  %div.form-group
    = label_tag nil, 'Collections:', :class => 'col-xs-12 col-sm-2 control-label'
    %div.col-xs-12.col-sm-10.new-problem-collections
      - Collection.accessible_by(current_ability, :manage).each do |collection|
        %div.new-problem-collection
          = check_box_tag "collections[#{collection.id}]", 1,  !!(collection.problems.include? previous), class: 'checkbox', id: "collections_#{collection.id}"
          = label_tag "collections_#{collection.id}", collection.name.truncate(35), :title => collection.name

  %div.form-group
    %div.col-sm-2
    %div.col-xs-12.col-sm-10
      = select_tag :privacy, privacy_options(previous ? previous.is_public : false), :id => nil, :class => 'form-control'

  %div.form-group
    %div.col-sm-2
    %div.col-xs-12.col-sm-10
      %p.message
      - submit_msg = previous ? 'Update Collections' : 'Create question'
      = submit_tag submit_msg, :class => 'btn btn-primary'

app/views/problems/_collection_buttons.haml
%div.collection-buttons
  Your Collections:
  - Collection.accessible_by(current_ability, :manage).each do |collection|
    = form_tag problem_path(:id => problem.id), :method => :put do
      - selected = collection.problems.include? problem
      = hidden_field_tag :collection, collection.id, :id => nil
      = submit_tag collection.name.truncate(35), :id => "toggle_collection_#{collection.id}_#{problem.id}", :class => "collection-button btn #{selected ? 'btn-info' : 'btn-default'}", :title => collection.name, :style => "display :#{selected ? 'block' : 'none'}"

app/views/problems/_collection_text.haml
%div.collection-checkbox-text
  Belongs to collections:
  - Collection.accessible_by(current_ability, :manage).each do |collection|
    = form_tag problem_path(:id => problem.id), :method => :put do
      - selected = collection.problems.include? problem
      = hidden_field_tag :collection, collection.id, :id => nil
      %div{:style => "display :#{selected ? 'block' : 'none'}", :id => "collection_text_#{collection.id}_#{problem.id}", :class => "collection-text"}
        #{collection.name.strip}

app/views/problems/_history_list.html.haml
- problem.history.each do |prob|
  %hr
  - if can? :read, prob
    = prob.html5.html_safe
  - else
    %p Private problem

app/views/problems/_minor_form.html.haml
- previous = local_assigns[:previous] || nil
- source = @ruql_source || (previous && previous.ruql_source(false)) || ''
- tags = (previous && previous.tags.map(&:name).join(', ')) || ''

= form_tag edit_minor_path, :method => :post, :class => 'form-horizontal new-form'  do

  %div.form-group{:class => "edit-form"}
    = label_tag :ruql_source, 'Source:', :class => 'col-xs-12 col-sm-2 control-label'
    %div.col-xs-12.col-sm-10
      = text_area_tag :ruql_source, source, :class => 'source_field form-control', :rows => 15, :placeholder => 'RuQL source code'

  %div.form-group{:style => 'display: none'}
    = label_tag :parent_uid, 'Parent:', :class => 'col-xs-12 col-sm-2 control-label'
    %div.col-xs-12.col-sm-10
      = text_field_tag :parent_uid, nil, :id => nil, :class => 'form-control', :placeholder => 'Parent UID', :value => (previous.uid if previous)



  %div.form-group
    %div.col-sm-2
    %div.col-xs-12.col-sm-10
      %p.message
      = submit_tag "Confirm Update", :class => 'btn btn-default btn-update'

  %div.form-group{:class => 'confirm-edit', :style => 'display: none'}
    %label
      You only want to update question when making minor edits.
      %br
      Large-scale edits are more suitable for creating a new question by hitting supersede.
      %br
      Are you sure you still want to continue?
    = submit_tag "Yes. Proceed!", :class => 'btn btn-default'
    %button{:type => "button", :class => "no-edit btn btn-default"}
      No. Go Back!

app/views/problems/_problem_data.html.haml
- if can? :add_tags, problem
  - if column == :checkbox
    = check_box_tag "checked_problems[#{problem.id}]", 1, false, id: "checked_problems_#{problem.id}",
      class: "checkbox check_box_#{group_id}", form: "update_multiple_tags_#{group_id}"

- if can? :add_to_collection,problem
  - if column == :stats
    - stats = problem.attempt_stats
    %div.stats{:id => "stats_#{problem.id}"}
      %div.plain_text
        = "Successful First Attempt Percentage:"
        %p.first_success_rate
          = (1.0 * stats["first_correct"]) / stats["first_attempts"] * 100
        = "overallAttempts:"
        %p.overallAttempts
          = stats["overallAttempts"]
        = "Wrong of All Attempts:"
        %p.allAttemptsWrongAmount
          = stats["allAttemptsWrongAmount"]

        = "Total First Attempts:"
        %p.total_first_attempts
          = stats["first_attempts"]
        = "Wrong First Attempts:"
        %p.wrong_first_attempts
          = stats["first_attempts"] - stats["first_correct"]
        = "Correct First Attempts:"
        %p.correct_first_attempts
          = stats["first_correct"]
        = "Entrys Distribution:"
        %p.entrys_array
          = stats["entry_attempts"].to_s
      %div.first_graph{:id => "first_graph_#{problem.id}"}
        = "PlaceHolder"
      %div.total_graph{:id => "total_graph_#{problem.id}"}
        = "PlaceHolder"
      %div.entrys_graph{:id => "entrys_graph_#{problem.id}"}
        = stats["entry_attempts"].to_s

- if column == :problem
  = render :partial => "problems/student_answer", :locals => {:test_problem => problem, :index => -1},:columns => [:checkbox, :problem]

  %div.additional
    %div.prob-right
      - if can? :set_privacy, problem
        = form_tag problem_path(:id => problem.id), :method => :put, :class => 'prob_privacy' do
          - name = ["Public", "Share", "Private"]
          - level = problem.access_level
          - if level == 1
            = hidden_field_tag :privacy, name[0], :id => nil
            = submit_tag (name[0]), :class => 'btn btn-default privacy-button'
          - elsif level == 2
            = hidden_field_tag :privacy, name[1], :id => nil
            = submit_tag (name[1]), :class => 'btn btn-default privacy-button'
          - else
            = hidden_field_tag :privacy, name[2], :id => nil
            = submit_tag (name[2]), :class => 'btn btn-default privacy-button'

      = form_tag problem_path(:id => problem.id), :method => :put, :class => 'prob_obsolete' do
        = hidden_field_tag :obsolete, problem.obsolete ? '0' : '1', :id => nil
        - if can? :set_privacy, problem
          = submit_tag (problem.obsolete ? 'Obsolete' : 'Mark obsolete'), :class => 'btn btn-default obsolete-button'
        - elsif problem.obsolete
          = submit_tag 'Obsolete', :class => 'btn btn-default obsolete-button', :disabled => true


    %div Created #{problem.created_date} by #{problem.instructor.name}

    - if can? :manage, problem
      %div UID: #{problem.uid}
    -#   = render :partial => 'problems/collection_checkboxes', :locals => {:previous => problem}

    - if can? :set_previous, problem
      %div{:style => 'display: none'}
        Previous version:
        = form_tag problem_path(:id => problem.id), :method => :put, :class => 'previous-form' do
          = text_field_tag :previous, nil, :id => nil, :class => 'form-control', :placeholder => 'Enter problem UID',
              :value => (problem.previous_version.uid if problem.previous_version)

    - if can? :add_to_collection, problem
      = render :partial => 'problems/collection_text', :locals => {:problem => problem}

    - if can? :add_to_collection, problem
      %div.hide_checkbox
        = submit_tag "Show All Collections", :id => "hide_checkbox_block", :class => "hide_checkbox btn btn-default", :title => "show"

      %div.edit-collections{:style => 'display: none'}
        - Collection.accessible_by(current_ability, :manage).each do |collection|
          - selected = collection.problems.include? problem
          %li.collection-checkbox-li
            %input{:type=>"checkbox", :id =>"collections_checkbox_#{collection.id}_#{problem.id}",:class=>"collection-checkbox", :checked=>selected, :action=>"/problems/#{problem.id}", :collection => collection.id, :problem => problem.id}
            =collection.name
        %div.show_checkbox
          = submit_tag "Hide Collections", :id => "show_checkbox_block", :class => "show_checkbox btn btn-default", :title => "hide", :style => 'display: none'


    - if can?  :bloom_categorize, problem
      %div.bloom-buttons
        Bloom category:
        - Problem.all_bloom_categories.each do |category|
          = form_tag problem_path(:id => problem.id), :method => :put do
            - selected = problem.bloom_category == category
            - if selected
              = hidden_field_tag :category, 'none', :id => nil
            - else
              = hidden_field_tag :category, category, :id => nil
            = submit_tag category, :class => "bloom-button btn #{selected ? 'btn-info' : 'btn-default'}"
    - else
      %p
        = problem.bloom_category

    - if can? :supersede, problem
      %div
        Edit question:
        %textarea{:id => "source_#{problem.id}", :value => "current_ruql", :style => "display: none"}= #{problem.ruql_source}
        %button{"data-clipboard-target" => "source_#{problem.id}", "data-clipboard-text" => "",
                :title => "", :id => "copy_source_button_#{problem.id}", :class => "d_clip_button btn btn-default",
                :value => "copy_source_button_#{problem.id}", :style => ('display: none' if not Rails.env.test?)}
          Clip Source Code

        = link_to "Supersede", supersede_path(:id => problem.id), :id => "supersede_button_#{problem.id}", :class => 'supersede_button btn btn-default', :value => "Supersede"
        = link_to "Update", minorupdate_path(:id => problem.id), :id => "minorupdate_button_#{problem.id}", :value => "Update", :class => 'minorupdate_button btn btn-default'

        - if !problem.previous_version.nil?
          = link_to "See Version History", problem_history_path(:id => problem.id), :id => "history_button_#{problem.id}", :class => 'history_button btn btn-default'

      %div.supersede_form.hidden-additional{:style => 'display: none'}
        = render :partial => 'problems/new_form', :locals => {:previous => problem}

      %div.history_list.hidden-additional{:style => 'display: none'}
        = render :partial => 'problems/history_list', :locals => {:problem => problem}
      %div.minor_form.hidden-additional{:style => 'display: none'}
        = render :partial => 'problems/minor_form', :locals => {:previous => problem}

- if can? :add_tags, problem
  - if column == :tags
    %div{:id => "all_tags_#{problem.id}", :class => 'tag_list'}
      = render :partial => 'problems/tags', locals: { problem: problem }

    = form_tag add_tags_path(id: problem.id), class: 'add_tags_form' do
      = text_field_tag :tag_names, nil, id: "add_tags_#{problem.id}", class: 'form-control', placeholder: 'Add tags'

app/views/problems/_problem_table.html.haml
- problems = problems.select{|p| can? :read, p}
- group_id = local_assigns[:group_id].nil? ? 0 : group_id

- if problems.empty? and !local_assigns[:empty_msg].nil?
  %h3= empty_msg

- else
  - if group_id == 0 and can? :manage, @collection
    = link_to 'New question', new_problem_path, :class => 'btn btn-primary'

  - if columns.include? :checkbox and (can? :add_tags, Problem)
    = form_tag update_multiple_tags_path, :id => "update_multiple_tags_#{group_id}", :class => 'check_form' do
      = text_field_tag :tag_names, nil, :id => nil, :class => 'form-control', :placeholder => 'tag 1, tag 2'
      = submit_tag 'Tag checked problems', :class => 'btn btn-primary'

  %div.table-responsive.problem_table
    %table.table.table-striped
      -if (can? :add_tags, Problem)
        %thead
          %tr
            - columns.each do |col|
              - if col == :checkbox
                %th= check_box_tag nil, 1, false, :id => "check_all_#{group_id}", :class => 'checkbox check_all', :style => 'display: none'
              - elsif col == :problem
                %th Question Text
              - elsif col == :stats
                %th Response Stats
              - elsif col == :tags
                %th Tags

      %tbody
        - problems.each do |problem|
          %tr
            - columns.each do |col|
              %td= render :partial => 'problems/problem_data', :locals => {:problem => problem, :column => col, :group_id => group_id}

app/views/problems/_tags.html.haml
- if can? :manage, problem
  - problem.tags.each do |tag|
    %div.tag
      = link_to tag.name, view_tags_path(:tag_names => tag.name), :class => 'btn btn-info'

      = form_tag remove_tags_path(:id => problem.id), :method => :post, :class => 'remove_tag' do
        = hidden_field_tag :tag_names, tag.name, :id => nil
        = button_tag :type => 'submit', :class => 'clr-button' do
          %div.glyphicon.glyphicon-remove

app/views/problems/add_collection.html.haml
%h4 Create new version of question:
%div.problem_box
  = @problem.html5.html_safe
  %div.additional Created #{@problem.created_date} by #{@problem.instructor.name}

= render :partial => 'add_to_collection'

app/views/problems/index.html.haml
%div#graph
  = "TEST"

%div#filter-sidebar
  = render :partial => 'filter'

%div#filter-content.container-fluid

  = render :partial => 'problem_table', :locals => {:problems => @problems, :columns => [:checkbox, :problem, :stats, :tags],
                                                    :empty_msg => 'No questions matched your search criteria'}


  - if !@problems.nil? and !@problems.select{|p| can? :read, p}.empty?
    %div.row#page_options
      %div.col-xs-6
        - [5, 30, 60].each do |n|
          = link_to "View #{n}", problems_path(:per_page => n)
      %div.col-xs-6
        = will_paginate @problems

app/views/problems/minorupdate.html.haml
%h4 Create new version of question:
%div.problem_box
  = @problem.html5.html_safe
  %div.additional Created #{@problem.created_date} by #{@problem.instructor.name}

= render :partial => 'minor_form', :locals => {:previous => @problem}

app/views/problems/new.html.haml
%h4 Create new question:

= render :partial => 'new_form'

app/views/problems/view_history.html.haml
%h4 History for question:
%div.problem_box
  = @problem.html5.html_safe
  %div.additional Created #{@problem.created_date} by #{@problem.instructor.name}

= render :partial => 'problems/history_list', :locals => {:problem => @problem}