config/routes.rb
Coursequestionbank::Application.routes.draw do

  root :to => 'problems#home'

  match  'auth/:provider/callback' => 'session#create'
  get 'auth/bypass/:user_id' => 'session#bypass', :as => 'bypass'
  post 'logout' => 'session#destroy'
  get  'auth/failure' => 'session#failure'
  get 'login' => 'session#login', :as => 'login'
  get 'upload' => 'upload#index', :as => 'upload'
  post 'upload' => 'upload#upload', ":as" => 'upload'

  resources :problems
  get 'problems/tags/:tag_names' => 'problems#view_tags', :as => 'view_tags'
  post 'problems/filters' => 'problems#set_filters', :as => 'set_filters'
  post 'problems/:id/tags/add' => 'problems#add_tags', :as => 'add_tags'
  post 'problems/:id/tags/remove' => 'problems#remove_tags', :as => 'remove_tags'
  post 'update_multiple_tags' => 'problems#update_multiple_tags'

  get 'problems/:id/supersede' => 'problems#supersede', :as => 'supersede'

  post 'problems/:id/minorupdate' => 'problems#minorupdate', :as => "minorupdate"
  get 'problems/:id/minorupdate' => 'problems#minorupdate', :as => "minorupdate"

  post 'problems/edit_minor' => 'problems#edit_minor', :as => "edit_minor"

  get 'problems/:id/history' => 'problems#view_history', :as => 'problem_history'

  get 'profile' => 'instructors#show', :as => 'profile'
  
  get 'admin' => 'instructors#admin', :as => 'admin'
  post 'admin/instructor' => 'instructors#update_instructor', :as => 'update_instructor'

  resources :studentanswers

  resources :collections
  post 'collections/search/' => 'collections#search', :as => 'search_collection'
  get 'collections/:id/export' => 'collections#export', :as => 'export'
  get 'collections/:id/preview' => 'collections#preview', :as => 'preview'
  get 'finalize_upload' => 'collections#finalize_upload'
  get 'collections/search/' => 'collections#search', :as => 'search_collection'

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base

  attr_accessible :name, :username, :uid, :provider, :provider_image, :provider_email, :privilege, :collections, :problem

  has_many :collections
  has_many :problems
  has_many :studentanswers
  
  def self.dev_users
    where(:provider => "developer")
  end

  def self.create_via_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      if auth["info"]["name"] and !auth["info"]["name"].empty?
        user.name = auth["info"]["name"]
      else
        user.name = auth["info"]["nickname"]
      end
      user.username = auth["info"]["nickname"]
      user.provider_image = auth["info"]["image"]
      user.provider_email = auth["info"]["email"]
      user.privilege = "Student"
    end
  end

  # def admin?
  #   privilege == "Admin"
  # end
  #
  # def instructor?
  #   privilege == "Instructor"
  # end
  #
  # def student?
  #   privilege == "Student"
  # end

  # The new data structure stores privilege information in Instructor
  # To prevent data loss, the old whitelist table is preseved.
  # If the privilege attribute is nil in instructor table, find that user in whitelist
  # And set his privilege in instructor table as in whitelist
  # If somehow a user's privilege is nil in instructors and whitelist table
  # set him as Student
  # (this should not happen in practice, though)
  def get_privilege
    if self.privilege.nil?
      whitelist = Whitelist.find_by_username_and_provider(username, provider)
      if whitelist
        self.privilege = whitelist.privilege.capitalize
      else
        self.privilege = "Student"
      end
    end
    return self.privilege
  end

  def self.privilege_levels
    %w{Admin Instructor Student}
  end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  def show
    session[:filters] = nil
    authorize! :manage, Collection
    @heading = 'Your collections'
    @instructor = Instructor.find_by_id(@current_user)
    @collections = @instructor.collections.to_a
    render :template => 'collections/index'
  end

  # def mark_as_current
  #   Instructor.update(@current_user.id, {:current_collection => params[:id]})
  #   redirect_to profile_path
  # end

  def admin
    authorize! :manage, Instructor
    # @unauthorized_users = Instructor.all.select{|i| i.privilege.nil?}
    @instructor = Instructor.order(:username)
  end

  def update_instructor
    authorize! :manage, Instructor
    username = params[:username] ? params[:username].strip : nil
    provider = params[:provider]
    privilege = params[:privilege]

    if username == @current_user.username and provider == @current_user.provider and privilege != @current_user.privilege
      flash[:error] = "Can't change your own privilege level"
      redirect_to :back and return
    end

    # if username == ''
    #   flash[:error] = 'Please enter a username.'
    #   redirect_to :back and return
    # elsif !Whitelist.providers.include?(provider)
    #   flash[:error] = 'Please select a provider.'
    #   redirect_to :back and return
    # elsif !Whitelist.privilege_levels.include?(privilege)
    #   flash[:error] = 'Please select a privilege level.'
    #   redirect_to :back and return
    # end

    instructor = Instructor.find_by_username_and_provider(username, provider)
    # if whitelist
    instructor.update_attribute(:privilege, privilege)
    instructor.touch
    # else
    #   Whitelist.create(:username => username, :provider => provider, :privilege => privilege)
    # end
    flash[:notice] = "#{instructor.username} is now #{instructor.get_privilege}."
    redirect_to :back
  end

  # def delete_whitelist_entry
  #   authorize! :manage, Instructor
  #   instructor = Instructor.find(params[:id])
  #
  #   if whitelist.username == @current_user.username and whitelist.provider == @current_user.provider
  #     flash[:error] = "Can't change your own privilege level"
  #     redirect_to :back and return
  #   end
  #
  #   whitelist.destroy
  #   flash[:notice] = 'Whitelist entry removed'
  #   redirect_to :back
  # end

  # def toggle_whitelist
  #   authorize! :manage, Whitelist
  #   Whitelist.is_enabled = !Whitelist.is_enabled
  #   flash[:notice] = Whitelist.is_enabled ? 'Whitelist enabled.' : 'Whitelist disabled.'
  #   redirect_to :back
  # end

end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/views/instructors/admin.html.haml
%div.section_title
  %h3 Manage User Access Level

// %div.section_options
//   = form_tag toggle_whitelist_path do
//     = button_tag :type => 'submit', :class => 'btn btn-primary' do
//       = Whitelist.is_enabled ? 'Disable whitelist' : 'Enable whitelist'

%div.section_body

  %div.table-responsive
    %table.table.users-table
      %thead
        %tr
          %th Username
          %th Provider
          %th Privilege
          %th
          %th

      %tbody
        // %tr#whitelist-new
        //   %td= text_field_tag :username, nil, :id => 'new-username', :class => 'form-control', :form => "whitelist-form-new", :placeholder => 'Username'
        //   %td= select_tag :provider, options(Whitelist.providers, 'Provider'), :id => 'new-provider', :class => 'form-control', :form => "whitelist-form-new"
        //   %td= select_tag :privilege, options(Whitelist.privilege_levels, 'Privilege'), :id => 'new-privilege', :class => 'form-control', :form => "whitelist-form-new"
        //   %td
        //     = form_tag update_whitelist_path, :id => "whitelist-form-new" do
        //       = submit_tag 'Add to whitelist', :class => 'btn btn-primary', :id => 'new-submit'
        //   %td
        - @instructor.each do |entry|
          %tr
            %td= entry.username
            %td= entry.provider
            %td= select_tag :privilege, options(Instructor.privilege_levels, entry.get_privilege), :id => "privilege_#{entry.uid}", :class => 'form-control', :form => "instructor-form-#{entry.id}"
            %td
              = form_tag update_instructor_path, :id => "instructor-form-#{entry.id}" do
                = hidden_field_tag :username, entry.username, :id => nil
                = hidden_field_tag :provider, entry.provider, :id => nil
                = submit_tag 'Update', :class => 'btn btn-primary', :id => "update_#{entry.uid}"
            -# %td
            -#   = form_tag whitelist_entry_path(:id => entry.id), :method => :delete do
            -#     = button_tag :type => 'submit', :class => 'clr-button' do
            -#       %span.glyphicon.glyphicon-remove