config/routes.rb
Coursequestionbank::Application.routes.draw do

  root :to => 'problems#home'

  match  'auth/:provider/callback' => 'session#create'
  get 'auth/bypass/:user_id' => 'session#bypass', :as => 'bypass'
  post 'logout' => 'session#destroy'
  get  'auth/failure' => 'session#failure'
  get 'login' => 'session#login', :as => 'login'
  get 'upload' => 'upload#index', :as => 'upload'
  post 'upload' => 'upload#upload', ":as" => 'upload'

  resources :problems
  get 'problems/tags/:tag_names' => 'problems#view_tags', :as => 'view_tags'
  post 'problems/filters' => 'problems#set_filters', :as => 'set_filters'
  post 'problems/:id/tags/add' => 'problems#add_tags', :as => 'add_tags'
  post 'problems/:id/tags/remove' => 'problems#remove_tags', :as => 'remove_tags'
  post 'update_multiple_tags' => 'problems#update_multiple_tags'

  get 'problems/:id/supersede' => 'problems#supersede', :as => 'supersede'

  post 'problems/:id/minorupdate' => 'problems#minorupdate', :as => "minorupdate"
  get 'problems/:id/minorupdate' => 'problems#minorupdate', :as => "minorupdate"

  post 'problems/edit_minor' => 'problems#edit_minor', :as => "edit_minor"

  get 'problems/:id/history' => 'problems#view_history', :as => 'problem_history'

  get 'profile' => 'instructors#show', :as => 'profile'
  
  get 'admin' => 'instructors#admin', :as => 'admin'
  post 'admin/instructor' => 'instructors#update_instructor', :as => 'update_instructor'

  resources :studentanswers

  resources :collections
  post 'collections/search/' => 'collections#search', :as => 'search_collection'
  get 'collections/:id/export' => 'collections#export', :as => 'export'
  get 'collections/:id/preview' => 'collections#preview', :as => 'preview'
  get 'finalize_upload' => 'collections#finalize_upload'
  get 'collections/search/' => 'collections#search', :as => 'search_collection'

end

app/views/layouts/application.html.haml
%link{:href => '//fonts.googleapis.com/css?family=Droid+Serif|Open+Sans:400,800,700', :rel => 'stylesheet', :type => 'text/css'}


%html
  %head
    %title Course Question Bank
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{:name => 'viewport', :content => 'initial-scale=1'}

  %body
    %div#header
      #banner
        = link_to image_tag('foxinboxheader.png'), problems_path
        - if @current_user
          #welcome_message Welcome, #{user_display_name(@current_user)}, #{@current_user.get_privilege}!
          %ul
            %li= link_to 'Home', problems_path, :class => 'btn btn-info'
            - if can? :manage, Collection
              %li= link_to 'My Collections', profile_path, :class => 'btn btn-info'
            %li= link_to 'Public Collections', collections_path, :class => 'btn btn-info'
            - if can? :manage, Whitelist
              %li= link_to 'Admin', admin_path, :class => 'btn btn-info'
            %li
              = form_tag logout_path, :method => :post do
                = submit_tag 'Log Out', :class => 'btn btn-info'
            %li= link_to 'Help', 'https://github.com/hrzlvn/coursequestionbank', :class => 'btn btn-info', :target => '_blank'

      %div#flash_message
        - if flash[:notice]
          %p.message= flash[:notice]
        - elsif flash[:warning]
          %p.message= flash[:warning]
        - elsif flash[:error]
          %p.message= flash[:error]

    %div#main
      = yield